# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'xx' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for turbo


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

end
